SET (CMAKE_C_COMPILER               "mpicc")
SET (CMAKE_C_FLAGS                  "-Wall -std=c99")
SET (CMAKE_C_FLAGS_DEBUG            "-g")
SET (CMAKE_C_FLAGS_MINSIZEREL       "-Os -DNDEBUG")
SET (CMAKE_C_FLAGS_RELEASE          "-O4 -DNDEBUG")
SET (CMAKE_C_FLAGS_RELWITHDEBINFO   "-O2 -g")

SET (CMAKE_CXX_COMPILER             "mpic++")
SET (CMAKE_CXX_FLAGS                "-Wall -std=c++14")
SET (CMAKE_CXX_FLAGS_DEBUG          "-g")
SET (CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELEASE        "-O4 -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g")

#SET (CMAKE_AR                       "llvm-ar-3.8")
#SET (CMAKE_LINKER                   "llvm-ld-3.8")
#SET (CMAKE_NM                       "llvm-nm-3.8")
#SET (CMAKE_OBJDUMP                  "llvm-objdump-3.8")
#SET (CMAKE_RANLIB                   "llvm-ranlib-3.8")
SET (CMAKE_C_COMPILER               "mpicc")
SET (CMAKE_C_FLAGS                  "-Wall -std=c99")
SET (CMAKE_C_FLAGS_DEBUG            "-g")
SET (CMAKE_C_FLAGS_MINSIZEREL       "-Os -DNDEBUG")
SET (CMAKE_C_FLAGS_RELEASE          "-O4 -DNDEBUG")
SET (CMAKE_C_FLAGS_RELWITHDEBINFO   "-O2 -g")

SET (CMAKE_CXX_COMPILER             "mpic++")
SET (CMAKE_CXX_FLAGS                "-Wall -std=c++14")
SET (CMAKE_CXX_FLAGS_DEBUG          "-g")
SET (CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELEASE        "-O4 -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g")

#SET (CMAKE_AR                       "llvm-ar-3.8")
#SET (CMAKE_LINKER                   "llvm-ld-3.8")
#SET (CMAKE_NM                       "llvm-nm-3.8")
#SET (CMAKE_OBJDUMP                  "llvm-objdump-3.8")
#SET (CMAKE_RANLIB                   "llvm-ranlib-3.8")

SET (CMAKE_EXE_LINKER_FLAGS         "-L/usr/lib/llvm-10/lib")
SET (CMAKE_MODULE_LINKER_FLAGS      "-L/usr/lib/llvm-10/lib")
SET (CMAKE_SHARED_LINKER_FLAGS      "-L/usr/lib/llvm-10/lib")
SET (CMAKE_STATIC_LINKER_FLAGS      "-L/usr/lib/llvm-10/lib")
