# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Messages.proto',
  package='pcap_analyzer',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0eMessages.proto\x12\rpcap_analyzer\"\xcd\x01\n\x10\x43onnectionNotify\x12\x0c\n\x04hash\x18\x01 \x02(\t\x12\x13\n\x0btimestamp_s\x18\x02 \x02(\x04\x12\x14\n\x0ctimestamp_us\x18\x03 \x02(\x04\x12\x10\n\x08protocol\x18\x04 \x02(\r\x12\x0b\n\x03src\x18\x05 \x02(\t\x12\x0b\n\x03\x64st\x18\x06 \x02(\t\x12\x13\n\x0bl4_protocol\x18\x07 \x02(\r\x12\x0e\n\x06l4_src\x18\x08 \x02(\r\x12\x0e\n\x06l4_dst\x18\t \x02(\r\x12\x0f\n\x07msgtype\x18\n \x02(\r\x12\x0e\n\x06seqnum\x18\x0b \x02(\r\"P\n\x15\x43onnectionCloseNotify\x12\x0c\n\x04hash\x18\x01 \x02(\t\x12\x13\n\x0btimestamp_s\x18\x02 \x02(\x04\x12\x14\n\x0ctimestamp_us\x18\x03 \x02(\x04\"\x9f\x01\n\x0eGenericMessage\x12\x36\n\x07msgtype\x18\x01 \x02(\x0e\x32%.pcap_analyzer.GenericMessage.MsgType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\"G\n\x07MsgType\x12\x15\n\x11\x43ONNECTION_NOTIFY\x10\x01\x12\x1b\n\x17\x43ONNECTION_CLOSE_NOTIFY\x10\x02\x12\x08\n\x04SYNC\x10\x03'
)



_GENERICMESSAGE_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='pcap_analyzer.GenericMessage.MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECTION_NOTIFY', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTION_CLOSE_NOTIFY', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYNC', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=412,
  serialized_end=483,
)
_sym_db.RegisterEnumDescriptor(_GENERICMESSAGE_MSGTYPE)


_CONNECTIONNOTIFY = _descriptor.Descriptor(
  name='ConnectionNotify',
  full_name='pcap_analyzer.ConnectionNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='pcap_analyzer.ConnectionNotify.hash', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_s', full_name='pcap_analyzer.ConnectionNotify.timestamp_s', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_us', full_name='pcap_analyzer.ConnectionNotify.timestamp_us', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='pcap_analyzer.ConnectionNotify.protocol', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src', full_name='pcap_analyzer.ConnectionNotify.src', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst', full_name='pcap_analyzer.ConnectionNotify.dst', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l4_protocol', full_name='pcap_analyzer.ConnectionNotify.l4_protocol', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l4_src', full_name='pcap_analyzer.ConnectionNotify.l4_src', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l4_dst', full_name='pcap_analyzer.ConnectionNotify.l4_dst', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgtype', full_name='pcap_analyzer.ConnectionNotify.msgtype', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='pcap_analyzer.ConnectionNotify.seqnum', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=239,
)


_CONNECTIONCLOSENOTIFY = _descriptor.Descriptor(
  name='ConnectionCloseNotify',
  full_name='pcap_analyzer.ConnectionCloseNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='pcap_analyzer.ConnectionCloseNotify.hash', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_s', full_name='pcap_analyzer.ConnectionCloseNotify.timestamp_s', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_us', full_name='pcap_analyzer.ConnectionCloseNotify.timestamp_us', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=321,
)


_GENERICMESSAGE = _descriptor.Descriptor(
  name='GenericMessage',
  full_name='pcap_analyzer.GenericMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgtype', full_name='pcap_analyzer.GenericMessage.msgtype', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='pcap_analyzer.GenericMessage.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GENERICMESSAGE_MSGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=483,
)

_GENERICMESSAGE.fields_by_name['msgtype'].enum_type = _GENERICMESSAGE_MSGTYPE
_GENERICMESSAGE_MSGTYPE.containing_type = _GENERICMESSAGE
DESCRIPTOR.message_types_by_name['ConnectionNotify'] = _CONNECTIONNOTIFY
DESCRIPTOR.message_types_by_name['ConnectionCloseNotify'] = _CONNECTIONCLOSENOTIFY
DESCRIPTOR.message_types_by_name['GenericMessage'] = _GENERICMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectionNotify = _reflection.GeneratedProtocolMessageType('ConnectionNotify', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONNOTIFY,
  '__module__' : 'Messages_pb2'
  # @@protoc_insertion_point(class_scope:pcap_analyzer.ConnectionNotify)
  })
_sym_db.RegisterMessage(ConnectionNotify)

ConnectionCloseNotify = _reflection.GeneratedProtocolMessageType('ConnectionCloseNotify', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONCLOSENOTIFY,
  '__module__' : 'Messages_pb2'
  # @@protoc_insertion_point(class_scope:pcap_analyzer.ConnectionCloseNotify)
  })
_sym_db.RegisterMessage(ConnectionCloseNotify)

GenericMessage = _reflection.GeneratedProtocolMessageType('GenericMessage', (_message.Message,), {
  'DESCRIPTOR' : _GENERICMESSAGE,
  '__module__' : 'Messages_pb2'
  # @@protoc_insertion_point(class_scope:pcap_analyzer.GenericMessage)
  })
_sym_db.RegisterMessage(GenericMessage)


# @@protoc_insertion_point(module_scope)
